name: 冬瓜签到
#https://gitee.com/lxk0301/jd_scripts/raw/master/jd_bean_sign.js
#https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
#测试冬瓜签到
on:
    # push:
    #     branches:
    #         - master
    schedule:
        - cron: "5 1 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: npm install
              run: |
                  npm install
            - name: "运行 【冬瓜签到.】"
              run: |
                  node 冬瓜钱到.js
              env:
                  SYNCURL: https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  EFORK: ${{ secrets.EFORK }}
